#!/usr/bin/env bash

npm run build
npm lint test
npm run lint

standard-version --no-verify

# Push changes into the current branch
git rev-parse --abbrev-ref HEAD | xargs git push origin

git push --tags

npm publish
