#!/usr/bin/env bash

npm run build
standard-version --no-verify

# Push changes into the current branch
git rev-parse --abbrev-ref HEAD | xargs git push origin

git push --tags

npm publish --access=public
