#!/usr/bin/env sh

set -e
rm -rf dist coverage

if [[ -z "${CI}" ]]; then
    echo "Detected no CI-environment, will use npm i"
    npm i
else
    echo "Detected CI-environment, will use npm ci"
    npm ci
fi
