#!/usr/bin/env sh

set -e
export PATH=node_modules/.bin:$PATH

if [[ -z "${CI}" ]]; then
    echo "Detected no CI-environment, will test with ts-node"
    nyc _mocha -r ts-node/register -r jsdom-global/register 'src/**/*.spec.ts'
else
    echo "Detected CI-environment, will test directly"
    [[ -f /wait ]] && /wait
    MOCHA_FILE=coverage/tests/mocha/results.xml nyc _mocha -r jsdom-global/register --reporter mocha-junit-reporter 'dist/**/*.spec.js'
fi


